//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackatonAnketApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblBlock
    {
        [Key]
        public int blockId { get; set; }
        public Nullable<int> oyId { get; set; }
        public Nullable<int> blockNo { get; set; }
        public Nullable<int> nonce { get; set; }
        public string prevHash { get; set; }
        public string blockHash { get; set; }
    
        public virtual tblOy tblOy { get; set; }
    }
}
