//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackatonAnketApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblKullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKullanici()
        {
            this.tblOy = new HashSet<tblOy>();
        }
        [Key]
        public int kId { get; set; }
        public string tc { get; set; }
        public string sifre { get; set; }
        public string adSoyad { get; set; }
        public string tel { get; set; }
        public string adres { get; set; }
        public Nullable<int> yas { get; set; }
        public string ogrenimDurum { get; set; }
        public Nullable<int> durum { get; set; }
        public string mail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOy> tblOy { get; set; }
    }
}
